In [11]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [13]:
#load the data sets
df = pd.read_csv("Salary_datasets .csv")
df.head()

   years_experience  salary
0               3.7   32610
1               9.5   61447
2               7.3   51729
3               6.0   42857
4               1.6   30797

In [16]:
#Divide the data into X and Y 
x= df['years_experience']
y= df['salary']

In [17]:
x

0      3.7
1      9.5
2      7.3
3      6.0
4      1.6
      ...
195    3.5
196    7.3
197    9.0
198    8.9
199    7.8
Name: years_experience, Length: 200, dtype: float64

In [18]:
y

0      32610
1      61447
2      51729
3      42857
4      30797
       ...
195    29528
196    48695
197    57860
198    58983
199    57526
Name: salary, Length: 200, dtype: int64

In [26]:
#train and splitting
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [37]:
x_train=np.array(x_train).reshape(-1,1)

In [38]:
#Train model linear Regression
from sklearn.linear_model import LinearRegression
#load the model
lr = LinearRegression()

# training model on X_train and y_train 
model = lr.fit(x_train, y_train)

In [39]:
#predication X_test 
y_pred=model.predict(x_test.values.reshape(-1,1))

In [43]:
data=pd.DataFrame({'Actual':y_test, 'Predicted': y_pred,'diff':y_test-y_pred})
data.head(10)

     Actual     Predicted         diff
95    38090  40247.414439 -2157.414439
15    31790  26199.377506  5590.622494
30    42237  45685.364219 -3448.364219
158   28147  28918.352396  -771.352396
128   18791  18495.615317   295.384683
115   52860  57467.588744 -4607.588744
69    56948  62905.538524 -5957.538524
170   46145  48857.501591 -2712.501591
174   50724  47498.014146  3225.985854
45    48161  47951.176628   209.823372

In [44]:
from sklearn.metrics import r2
r2 = data(y_test, y_pred)
print("R2 Score:", r2)

ImportError: cannot import name 'r2' from 'sklearn.metrics' (C:\Users\rmnav\anaconda3\Lib\site-packages\sklearn\metrics\__init__.py)